{% set name = "perses" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/choderalab/perses/archive/{{ version }}.tar.gz
  sha256: 9023af941159ef9a50563460348c71d9a428b8325ac030909a67a9cfea46d68c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  entry_points:
    - perses-relative = perses.app.setup_relative_calculation:run
    - perses-fah = perses.app.fah_generator:run

requirements:
  host:
    - python >=3.6
    - pip
    - numpy
  run:
    - python >=3.6
    - numpy
    - scipy
    - numba
    - netcdf4
    - matplotlib-base
    - seaborn
    - networkx >=2.0
    - dask
    - distributed
    - tqdm
    - pyyaml
    - pandas
    - pymol-open-source
    - dask-jobqueue
    - dicttoxml
    - fire
    - joblib
    - mdtraj
    - pymbar ==3.0.3
    - ambertools >=19.11
    - openmm >=7.4.2
    - openmmforcefields
    - openmoltools >=0.8.4
    - openmmtools >=0.20.0
    # - openeye-toolkits

test:
  imports:
    - perses
  # commands:
    # # these require openeye toolkits
    # - perses-relative --help
    # - perses-fah --help

about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Experiments with expanded ensemble simulation to explore chemical and mutational space
  description: |
    Experiments with expanded ensemble simulation to explore chemical and mutational space
  doc_url: http://perses.readthedocs.io/
  dev_url: https://github.com/choderalab/perses

extra:
  recipe-maintainers:
    - jaimergp
    - jchodera
    - mikemhenry
